import './components/itemsGraph';
import './components/itemsTable';
import './components/itemsTree';
import './components/itemsVertical';
import './components/itemsHorizontal';
import './components/itemsHorizontalLinked';
import './components/router';
import './components/routerA';
import './components/console';
import './components/dialog';
import './components/button';

import './containers/app';
import './containers/pageArray';
import './containers/pageOrderedArray';
import './containers/pageBubbleSort';
import './containers/pageSelectSort';
import './containers/pageInsertionSort';
import './containers/pageStack';
import './containers/pageQueue';
import './containers/pagePriorityQueue';
import './containers/pageLinkList';
import './containers/pageMergeSort';
import './containers/pageShellSort';
import './containers/pagePartition';
import './containers/pageQuickSort1';
import './containers/pageQuickSort2';
import './containers/pageBinaryTree';
import './containers/pageRedBlackTree';
import './containers/pageHashTable';
import './containers/pageHashChain';
import './containers/pageHeap';
import './containers/pageGraphN';
import './containers/pageGraphD';
import './containers/pageGraphW';
import './containers/pageGraphDW';
import './containers/footer';

//TODO: move code from app here and imports spread to all files, where using some component, should be exact import