import './components/itemsHorizontal';
import './components/itemsVertical';
import './components/router';
import './components/routerA';
import './components/console';
import './components/dialog';
import './components/button';

import './containers/app';
import './containers/pageArray';
import './containers/pageOrderedArray';
import './containers/pageList';
import './containers/pageBubbleSort';
import './containers/pageSelectSort';
import './containers/pageInsertionSort';
import './containers/pageStack';
import './containers/pageQueue';
import './containers/pagePriorityQueue';
import './containers/footer';